INSERT INTO questions(string_question,id_category_question) VALUES ('Cuál es la validez del reconocimiento médico de clase II?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuándo el avión disponga de un transpondedor en servicio el piloto deberá activarlo:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando un avión disponga del modo “C” el piloto:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('La expresión vuelva a navegación propia quiere decir:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una zona de control se extenderá lateralmente como mínimo:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Para indicar al piloto que active los frenos el señalero:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Todo aviso conteniendo información relativa a Seguridad en Vuelo, Navegación Aérea o a cualquier asunto de naturaleza técnica administrativa o legal que tenga por origen el AIS se denomina:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué deberá hacer el piloto de un avión para alertar de sus problemas de comunicación  por radio si se ve obligado a aterrizar sin requerir ayuda inmediata?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El plan de vuelo para un vuelo controlado deberá presentarse al menos:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué letra de código deberá utilizarse para una calle de rodadura para aviones de un ancho de vía de 15 m?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('La categoría de un aeródromo referida a su capacidad  para el rescate y su lucha contra incendios se basa:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se considera Área de control CTA a:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las VMC mínimas para un espacio aéreo clasificado como “B” por encima de 10.000 pies:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('En qué sección del AIP se contiene información relativa  a áreas y/o rutas para los que se facilitan servicios meteorológicos:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las luces del extremo de la pista han de ser:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Salvo que se obtenga autorización por un centro ATC, un vuelo VFR no podrá acceder (ni abandonar) una zona de control con un techo inferior a:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las unidades responsables de fomentar una organización eficaz de los servicios de búsqueda y salvamento son:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('La distancia vertical entre un nivel, punto u objeto considerado como punto y una referencia especificada, corresponde a la:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El término genérico que significa indistintamente altura, altitud o nivel de vuelo, recibe el nombre de:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El área de movimiento de un aeródromo comprende:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('En la maniobra de estacionamiento el señalero cruza repetidamente los brazos por encima de la cabeza, el piloto debe actuar ante esta señal:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Para realizar un vuelo VFR a nivel de crucero 65 en un espacio aéreo de clase F, las mínimas VMC de visibilidad y distancias de las nubes son:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El techo de nubes corresponde a:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El control de aeródromo se encuentra generalmente asegurado con la ayuda de la radio',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una cruz blanca situada sobre la pista significa:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una serie de destellos blancos dirigida desde el control de aeródromo a una aeronave en tierra significa:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('A la altitud de transición se pasa:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('La CTR es un volumen:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un aeródromo situado en un espacio aéreo de clase “E” la visibilidad es de 1,5 Km Una aeronave que desee penetrar en VFR en ese espacio aéreo:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Referente a la prevención de colisiones, indique cual de las siguientes frases es cierta:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El tránsito aéreo lo constituyen todas las aeronaves:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Según indica la JAR-FCL 1110, el titular de una licencia PPL(A) no actuará como piloto al mando de un avión transportando pasajeros a no ser que:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El tiempo de vuelo comprende:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El tiempo que utilizan los servicios ATS, expresado en horas y minutos del día de 24 horas que comienza a media noche corresponde al:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('En el caso de que exista peligro de colisión entre dos aeronaves en rodaje en el área de maniobras de un aeródromo:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si una aeronave desea avisar que tiene dificultades que la obligan a aterrizar, pero no necesita asistencia inmediata:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('La tabla de niveles de crucero se utiliza en función de:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un aeródromo sin TWR la aeronave “A” realiza toma y despegueDetrás, otra aeronave “B” de superiores características tiene intención de realizar idéntica maniobra, pero realiza motor y al aire',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Volando con rumbo 350º el nivel de vuelo más bajo utilizable en un vuelo VFR, corresponde al:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Los vuelos VFR observarán las disposiciones referentes al servicio de control  de tránsito aéreo especificados en las reglas generales:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Los espacios aéreos de dimensiones definidas, dentro de las cuales se facilitan los servicios de información de vuelo y alerta son:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Justo antes de llegar a plataforma , al rodar inadvertidamente sobre la hierba la rueda se mete en un hoyo ocasionando serios desperfectos al avión y obligando a la tripulación a demorar la salida:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('En el sistema “VASIS”, cuántos focos luminosos hay en cada barra lateral?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una zona de control se extenderá lateralmente al menos:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se entiende por Centro de Servicios de Tráfico Aéreo:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El servicio de alerta se prestará:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('La edad mínima para obtener una PPL es:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una bengala roja lanzada hacia un avión en vuelo significa:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si una autorización ATC no es adecuada para el piloto al mando, éste deberá:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El piloto debe formalizar un plan de vuelo antes de cada vuelo:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('En la casilla de reglas de vuelo de un plan de vuelo si vamos a hacer un vuelo IFR escribiremos la letra:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Para un vuelo no controlado el plan de vuelo deberá enmendarse si ha pasado un cierto tiempo respecto a la hora de salida',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cualquier cambio importante respecto del plan de vuelo VFR  presentado se notificará lo antes posible a la dependencia correspondiente de tránsito aéreo',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Debemos notificar a los servicios de tránsito aéreo la nueva hora de llegada, si la estimada de paso por el siguiente punto de notificación o de llegada al aeródromo de destino varía en +/-:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si volando dentro de una zona de control las condiciones meteorológicas empeoran quedando por debajo de las VMC, ¿Qué medida tomaría?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un suceso en el que la aeronave sufre daños o roturas estructurales que afectan adversamente a su resistencia estructural, su 7 o sus características de vuelo se denomina:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una desviación de la TAS de un 5% o más, con respecto a la consignada en el plan de vuelo deberá ser notificada',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las luces del umbral de la pista han de ser:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si queremos buscar información sobre zonas prohibidas ¿En qué sección del AIP buscaremos?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué avión tiene prioridad para aterrizar?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Volando en un FIR, ¿Qué servicios podemos esperar?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Qué significado tiene la fase de alerta:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando control da una instrucción a una aeronave y ésta no puede cumplirla o la situación no aconseja que lo haga, la aeronave deberá:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Principales funciones de la OACI:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('En una pista de 2000 metros sin delimitación de distancia  del punto de espera, el avión esperará a:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿De qué color es la baliza de identificación aeroportuaria?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una luz intermitente roja emitida  desde la torre de control durante la aproximación al aterrizaje, significará que:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Desde cuándo cuenta la validez del certificado médico?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Dónde y cuando se ratificaron los convenios de la OACI?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es la altitud mínima autorizada en áreas de control sobre terreno?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un estado en el AIS debe informar:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('De que color son las luces de alta intensidad de un obstáculo fijo:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cada cuanto se renueva el mensaje ATIS?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('En caso que una aeronave declare emergencia, el responsable de suministrar servicio de alerta será',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Los principales objetivos de la OACI son:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('La máxima autoridad en un avión en vuelo será :',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Tráfico esencial  es aquel vuelo controlado al que se puede aplicar separación prevista por el ATC que en relación a un vuelo controlado concreto no es',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las fases relativas a una supuesta emergencia son:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Todo aviso conteniendo información sobre el reglamento del aire, sobre tráfico aéreo y los procedimientos de navegación aérea, que se distribuyen anticipadamente a su fecha de entrada en vigor se denomina:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las luces de una calle de rodaje serán:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('En referencia a las reglas de vuelo si un vuelo primero sigue las reglas de vuelo instrumentales y después las reglas e vuelo visuales se insertara en la casilla reglas de vuelo',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se define fase de alerta como',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('La expresión contacto radar hace referencia a',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se define ASDA, distancia aceleración –parada disponible, como:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se define SWY, zona de parada, como:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un avión que va volando sobre el mar a una altura de 4500 ft sobre un espacio aéreo clase “F”, que condiciones de VMC se le exige:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si una  aeronave “A” con autorización ATC va volando dentro de los limites de un área de control y otra aeronave “B” sin autorización, se acerca a la primera en convergencia, ¿ que aeronave tiene prioridad de paso ?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando llevaremos el modo C del transpondedor encendido',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si un avión no posee transpondedor SSR, para identificarlo el controlador ATC puede solicitar que realice la siguiente maniobra:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('En caso de fallo de radio que código se deberá poner en el transpondedor:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('En caso de fallo de 4 de doble vía, que código se pondrá en el respondedor SSR:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Como debe responder una aeronave cuando ATC le de un determinado “ modo / código “ en su respondedor SSR:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El plan de vuelo para un vuelo VFR controlado debe enmendarse si ha pasado un determinado tiempo, ¿cuanto?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una desviación de la TAS, con respecto a la consignada en el plan de vuelo deberá ser notificada si es:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Los objetivos de los servicios de transito aéreo son :',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando un controlador ATC identifica positivamente a una aeronave en el radar:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El informe de posición de una aeronave debe contener en el siguiente orden:',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Que centros prestan servicios de transito aéreo?',1);
INSERT INTO questions(string_question,id_category_question) VALUES ('El viento en las capas bajas de la atmósfera debido al rozamiento',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si en un mapa isobárico observamos que éstas están muy juntas podemos esperar',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('La brisa de mar',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('En la brisa de montaña',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('La presencia de altocúmulos lenticulares indica',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Que es necesario para que se forme la niebla de radiación',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Que nubes son mas probables que se formen a baja cota',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cual es la temperatura mas propicia para que se forme hielo claro en el avión',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si en un informe meteorológico vemos la palabra BKN quiere decir',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Que significa la palabra NOSIG',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Como se da el viento en aviación',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('En el siguiente TAF',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('El sondeo  dice que la isoterma de 0º esta FL 080, calcular la temperatura estimada a FL 140',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Definición de viento FOENH es:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('A partir de que visibilidad se empieza a informar de RVR',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('A que tipo de nubes suele venir asociada la lluvia',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se define punto de rocío como:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Que tipo de nubes indican estabilidad en la atmósfera',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Donde esta mas alta la troposfera',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('En el hemisferio sur, como giran los vientos en los anticiclones',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuáles son las características de los vientos de superficie en áreas en las que los mapas meteorológicos muestran isobaras muy juntas entre sí ?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('En una circulación de brisa terrestre y marina, la brisa terrestre sopla:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es el periodo de validez de un TREND?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué pasa con el QNH y QNE cuando entra en un frente cálido?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al elaborar un plan de vuelo a nivel FL60¿Cuál de las siguientes cartas de viento y temperatura superiores serán las más próximas a su nivel de vuelo?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es la forma más efectiva de la disipación de nubes?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se define subsidencia como Subsidencia:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('LFBD 1524 26015KT 9999 SHRA BKN020 TEMPO 1620 26020G30KT
8000 +SHRA BKN015CB PROB30 TSRA=
En vuelo de Lisboa a Burdeos con ETA a las 18:00 UTC',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Nada más amanecer, condiciones necesarias de viento para la formación de nieblas:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Para calcular el QNH a partir del QFE se necesitan',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuáles son las condiciones para que se produzcan precipitaciones de aguanieve?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Antes del paso de un frente cálido?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué tipo de nubes muestran condiciones inestables?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué característica se asocia a la inversión de temperaturas?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué formación nubosa es más probable que se desarrolle a baja cota cuando una masa de aire cálido se superpone a una masa de aire frío?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cómo se encuentran descritas las nubes de tipo “CB separados” en la carta sobre condiciones meteorológicas significativas?:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('LECU 050700Z 34005 2500 RVR281500P RVR10 1500U VV 002 BCFG SCT003 BKN005 TEMPO 0708 30015 5000',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué es necesario para la formación de onda de montaña?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('En una clave cifrada  ¿Qué significan las siglas SCT?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('De las siguientes, ¿Cuáles son las nubes más bajas?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('De las siguientes nubes, ¿Cuáles son de inestabilidad?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Con una temperatura de 14ºC y un punto de rocío de 12ºC, ¿Qué es necesario para que se forme niebla?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las isobaras son líneas que unen puntos de igual presión en un momento dado y',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('En el hemisferio sur, ¿Cómo giran los vientos en los anticiclones?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('En el hemisferio norte, ¿Cómo giran los vientos en las borrascas?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Por qué el aire no se desplaza de las altas presiones a las bajas presiones directamente?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('De la relación que existe entre los gráficos de isobaras y la dirección del viento y fuerza del viento, podemos deducir que:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Dónde podemos encontrar la nube rotor en una onda de montaña?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('La información de viento:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si una masa de aire seco sube adiabática mente sin llegar a la saturación, esta se enfriará:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué medirá el altímetro de un avión situado en un aeropuerto situado a 540ft con un QNH de 993mb si el altímetro está calado a 1013hp?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Consulte el TAF del aeropuerto de Amsterdam',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál de los siguientes tipos de nubes es más probable que origine fuertes precipitaciones?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('En el calculo del QNH de un aeropuerto, la elevación del mismo se considera como atmósfera',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('A medida que vamos volando vemos nubes estratiformes cada vez mas altas, podemos afirmar que:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('El viento geostrófico respecto al de gradiente en un anticiclón es:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si tenemos en el aeropuerto un QNH de 1008Hpa y la elevación del mismo es de 1240 fts¿Qué marcará el altímetro calado con 1013Hpa?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un METAR de Paris nos dice que tenemos un viento de 300/15Kt¿Que viento podemos tener previsiblemente en altura?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('El espesor de la troposfera varia con:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cómo se encuentran las masas de aire distribuidas en una oclusión cálida?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('La base de nubes en los METAR y TAFs se da con referencia al:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué tipo de altitud se mantiene en el FL300?',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('La formación de las nubes de frente frío se produce:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('La fuerza de Coriolis es mínima en:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si volando nos encontramos nimbostratus, altocumulos y cirrus, por este orden, podemos esperar:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si volando nos encontramos una muralla de Cb junto un descenso de temperatura:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Los problemas mas importantes que plantea el vuelo a través de  un frente frió son:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('La altitud de densidad coincidirá con el nivel de vuelo siempre que:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un avión vuela a FL115 entre dos punto cuyos QNH son inicialmente 1030Hpa y posteriormente 1015Hpa',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('A la línea de intersección de una superficie frontal con la superficie de la tierra se le llama:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Para que se produzca niebla de radiación es necesario:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si en un METAR nos encontramos TSRA, significa:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si en un informe meteorológico con encontramos las siglas FC, significa:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un METAR encontramos la clave DZ, nos encontraremos:',3);
INSERT INTO questions(string_question,id_category_question) VALUES ('En los cálculos de masa y equilibrado, ¿Cual describe mejor el datum?',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Con un centro de gravedad en el limite mas adelantado que circunstancia podríamos esperar',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Suponiendo:
Peso total: 2900 KgEstación de la posición del centro de gravedad (cg): 1150
Estación limite trasera del cg: 1160
El peso máximo que se puede añadir a la estación 130',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('La posición del centro de gravedad de un avión, normalmente se calcula a lo largo del',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('La posición del centro de gravedad de un avión  esta a 7 metros de la línea que pasa por el datum, y su peso es de 49000 NEl momento correspondiente al datum será',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si el peso del avión es superior al inicialmente previsto, para una velocidad aerodinámica dada, el ángulo de ataque',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('La velocidad de entrada en perdida de un avión será máxima cuando se cargue con:',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando el centro de gravedad se encuentra en su posición delantera limite el avión se tomara',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('La máxima velocidad relativa indicada de un avión con motor alternativo en vuelo nivelado se alcanza',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se define pendiente de ascenso como la relación entre',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cual es el aspecto más importante de la zona trasera de las curvas de potencia',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un viento de frente constante',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('En ascenso no acelerado',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Que efecto tiene el viento en cola sobre la velocidad de máxima autonomía',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un viento de frente',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una componente de viento de frente que aumenta con la altitud, en comparación con una  condición de viento cero, suponiendo IAS constante',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una componente constante de viento de frente',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una mayor temperatura del aire exterior',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('La altitud de densidad es',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Con los siguientes datos, hallar el centro de gravedad:

BEW: 985 lbs        746
Piloto/copiloto: 2   724
Equipaje: 242 lbs   799
Aceite: 8 lbs        -52
Combustible: 45 US Gal',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Definimos la velocidad de mejor ángulo de ascenso como:',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('En la carrera de despegue que resulta más decisivo',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('De los siguientes factores cual será mas determinante para la carrera de despegue',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al considerar los efectos de un aumento en el peso de un avión ¿Cuál de los siguientes enunciados es cierto?',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('El avión cuando esta bajo el efecto suelo',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('De las siguientes cual afirmación no es verdadera',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('En el momento que el avión despega',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('La condición más peligrosa para el vuelo será',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Durante un viraje la sustentación:',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('El desplazamiento del peso causado al sacar el tren de aterrizaje',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Referente a los conceptos relacionados con el peso y centrado, indique cuál de las siguientes frases NO es cierta:',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se dice que un avión es neutralmente estable.Por ello es probable:',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('El centro de gravedad de un cuerpo es el punto',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('La masa de un avión es de 1950 Kg.Si se añaden 450 Kg en la bodega a 175 metros del centro de gravedad (cg) el centro de gravedad cargado (cg) se desplazara',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si el tren de morro se desplaza hacia atrás durante la retracción, ¿Cómo afectará este movimiento a la posición del centro de gravedad (cg) del avión?',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las cargas deben afianzarse debidamente en aras a:',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Hallar la posición del centro de gravedad en % de la MAC si la distancia desde el Datum a la LEMAC es de 13 metros, la distancia al TEMAC es de 19 metros y la distancia desde el datum al centro de gravedad es de 15 metros',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Hallar la posición del centro de gravedad si la MAC mide 8 metros y desde el datum al centro de gravedad hay una distancia de 8 metros y sabiendo que desde el datum a TEMAC hay 12 metros',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si tenemos el centro de gravedad situado a 101,2 pulgadas y el limite trasero es de 104, pulgadas, cuanto peso podremos cambiar de la estación 1125 a la estación 123,45 TOW=3140 lbs',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Hallar cuanto varia la posición del centro de gravedad si añadimos 400 lbs el la estación 97,8 TOW = 2850 CG=101,67',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se despega siempre contra el viento por que:',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Señalar lo incorrecto durante un despegue',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cual de las siguientes configuraciones es mas ventajosa a la hora de realizar un máximo planeo:',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Calcular el centro de gravedad de un avión con respecto al datum sabiendo que el peso del avión sobre la rueda de morro es de 8400 Lbs y sobre cada una de las patas del tren principal 20400 Lbs y sobre cada una de las patas del tren principal 20000 Lbs respectivamenteLa distancia al datum del tren de morro es de 94”  y la que existe hasta el tren principal es de 471”600 y 21',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si el centro de gravedad esta en el 25% de la MAC del avión, el centro de gravedad esta a 25% de:',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si un día tenemos en el aeropuerto de salida una PA baja, ¿cuál será la correcta?',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un descenso con viento en cara:',7);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál de las siguientes características no se cumple en la Troposfera?',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('La composición química de la atmósfera terrestre es:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('La fisiología de la enfermedad descompresiva se rige según una de las siguientes leyes de los gases:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('El enunciado “la presión total de una mezcla de gases es igual a la suma de las presiones parciales de los gases que componen la mezcla”, corresponde a:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('El proceso de transporte de oxigeno se realiza mediante:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('La hipoxia que aparece en la altitud es consecuencia de:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('Por encima de que altitud entraremos en la llamada “fase critica”, al hablar de la hipoxia:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál puede ser la causa de la Hiperventilación?',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando la capacidad de la sangre esta disminuida para el transporte de oxigeno debido a la falta de hemoglobina, se produce hipoxia:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('Los canales semicirculares forman parte de:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('Los órganos otolíticos forma parte de:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una rotura timpánica da como resultado:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando la imagen óptica se forma delante de la retina hablamos de:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las ilusiones somatográvicas se pueden producir cuando nos sometemos a:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('La orientación espacial se consigue gracias a:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('Los canales semicirculares y los órganos otolíticos detectan respectivamente:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('La primera fase del estrés se conoce como:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué  sensación experimenta un piloto al virar para salir de un giro nivelado coordinado?',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('La hipoxia esta provocada por:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué parte del oído interno es responsable de la percepción del ruido?',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('La función principal de los glóbulos rojos es:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué parte del oído podría verse afectada por los cambios en la presión del aire que se producen durante el ascenso / descenso?',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('la trompa de Eustaquio es el conducto de paso existente entre:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('un piloto esta acostumbrado a aterrizar solamente en pistas anchas. Al efectuar aproximaciones a pistas mas cortas y/o estrechas, el piloto podrá tener la sensación de que se encuentra:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('Utilizar una lista de comprobación antes de la salida es contribuir a:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('En relación a la toma de decisiones, ¿cuál de las siguientes afirmaciones es correcta?',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('La utilización de las listas de comprobación debe efectuarse de manera tal que:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('En relación al efecto de los medicamentos sobre el rendimiento de los pilotos:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('El consumo de alcohol en pequeñas cantidades:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál de los siguientes pueden considerarse síntomas de Hipoxia?',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('Para evitar el vértigo en vuelo, deberíamos:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('La memoria de trabajo nos permite por ejemplo:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuáles son los síntomas fácilmente observables a simple vista de un cuadro de estrés?',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al espirar, el aire expulsado contiene:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('El porcentaje en volumen de oxigeno presente en la atmósfera es de un 21%, que a su vez:',2);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se define noche como:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando una aeronave escuche un mensaje de peligro de otra aeronave deberá:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando una aeronave vea a otra que está en una situación de peligro el piloto al mando deberá:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Respecto a los cinturones de la tripulación de vuelo indicar cuál de las siguientes respuestas es correcta:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuál de siguiente equipo es obligatorio en un vuelo VFR:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuál es el equipo necesario para un vuelo nocturno:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('El radio radiotransmisor de activación automática que da la posición del avión en caso de impacto es:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Todas las aeronaves ostentarán luces de navegación situadas en los planos que serán:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuál de las siguientes fases se considera de emergencia:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se considera accidente cuando:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('De los siguientes instrumentos cuál NO es necesario para un vuelo VFR:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una aeronave en vuelo ve una “V” en el suelo. ¿Qué significado tiene?',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('El piloto al mando será responsable de comprobar antes de despegar que:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuáles son las reservas de combustible y aceite mínimas que se especifican en el anexo 6 parte II?:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Según el Anexo 6 parte II el piloto al mando será responsable de:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('La operación de aeronave distinta de la de transporte aéreo comercial o de los trabajos aéreos es:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Todos los miembros de la tripulación mantendrán abrochados sus cinturones de seguridad  mientras estén en sus puestos:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Todos los aviones en todos los vuelos irán equipados con:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Todos los aviones que realicen vuelos VFR llevarán:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Todos los aviones que operen de noche deberán llevar:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('En cuanto a las luces de navegación que deben ostentarse en el aire, son:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando el piloto al mando de una aeronave observe que otra aeronave se halla en situación de peligro:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando un piloto al mando de una aeronave capte un mensaje de socorro deberá:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una aeronave en emergencia usara el transpondedor con la clave:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('La frecuencia de emergencia en la banda VHF es:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una aeronave que este a punto de despegar cederá el paso a',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un aeródromo no controlado el piloto al mando',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cual de los siguientes es el Anexo de OACI que trata sobre la Operación de Aeronaves',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un aeropuerto con servicio de rodadura, en que momento seremos transferidos a la torre de control:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('En cuanto a las zonas de tratamiento especial',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si se produce un fuego en cabina, los tipos de extintores que podríamos usar son de:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('El ángulo de cobertura de las luces blancas obligatorias de posición, que brillan continuamente en vuelo y que se encuentran en la parte trasera de avión, es:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cual de los siguientes juegos de condiciones es el que tiene mas probabilidades de atraer aves hacia un aeropuerto?',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('De acuerdo con el documento 4444 de OACI, se aplicara una mínima separación, no radar, por estela turbulenta, de 3 minutos',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('La turbulencia de estela es mayor cuando el avión:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué factores son determinantes para la generación de vértices de estela?',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Los vértices generadores de turbulencia son masas de aire que tienden a derivar',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando se despega inmediatamente después de una aeronave de fuselaje ancho, que acaba de aterrizar, se deberá despegar:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('A temperatura ambiente elevada (¬¬¬¬¬¬¬+30ºC) y con humedad relativa baja como del 40%, el cielo despejado, sin niebla ni precipitaciones, la formación severa de hielo en el carburador:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Con una componente de cara lateral derecha de 5kts tras un avión en despegue:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('La luz verde de navegación obligatoria se encuentra en la punta del plano de estribor, con un ángulo de cobertura de:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('A la hora de determinar las condiciones mínimas operativas de un aeropuerto deberá tenerse en consideración:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('El riesgo de turbulencias de estela es máximo:',6);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si aplicamos la calefacción al carburador, la mezcla',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('El conjunto de eje del cigüeñal consiste en',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Para ajustar la relación de mezcla de un motor alternativo al aumentar la altitud deberemos',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Que condiciones pueden causar detonación',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al aumentar la altitud sin ajustar la relación de mezcla las prestaciones del motor de embolo se ven disminuidas por:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('En caso de fallo de motor en vuelo con un avión de hélice de revoluciones constantes, el ángulo de paso de la hélice adoptará:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('El ángulo de paso de una hélice de velocidad constante',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('La principal ventaja de una hélice de paso variable frente a la de uno fijo',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando actuamos sobre la palanca de mezcla el piloto',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si la fuente estática se bloquea durante el descenso, el altímetro',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('En vuelo la bola y el bastón se encuentran a la izquierda',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al volar de un sector de aire más cálido a otro mas frió',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('La presión recogida delante el tubo pitot es',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('El sector amarillo de un indicador de temperatura indica',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Color de la gasolina AVGAS 100LL:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('A nivel del suelo, ¿A qué equivale un hectopascal?',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Diferencia entre neumáticos de coche y de aviación:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué marca el indicador de presión de colector o manifold a motor parado en tierra?',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('En referencia a los magnetos son:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si un avión derrapa, ¿Qué tenemos que hacer para corregir el derrape?',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué determina el arco blanco en el anemómetro?',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al aplicar calor al carburador:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Para ajustar la relación de la mezcla en un motor alternativo al aumentar la altitud, habrá que:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las condiciones que pueden causar detonación son:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al aumentar la altitud sin ajustar la relación de la mezcla las prestaciones del motor del émbolo se ven afectadas por:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('En caso de fallo de motor en vuelo, las palas de una hélice de velocidad constante que impulsan a un monomotor que carezca de sistema de abanderamiento:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('El ángulo de paso de una hélice de velocidad constante:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('La ventaja principal de una hélice de velocidad constante en comparación con una hélice de paso fijo radica en:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando el piloto de un avión con motor alternativo mueve la palanca de mezcla a una posición de mezcla pobre:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('En vuelo, la aguja y la bola de un indicador de aguja y bola se encuentran a la izquierda, el avión está:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando volamos por niveles de vuelo, ¿Cómo calamos el altímetro?',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si a una batería de plomo de 12 voltios se le estropea una de las 12 células:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('En el hemisferio Sur durante la deceleración posterior a un aterrizaje en dirección Este la brújula:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Girando a la derecha en tierra, ¿Qué posición tienen la aguja y la bola?',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las baterías se clasifican según:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('En los carburadores modernos las variaciones en la relación de mezcla se obtienen ajustando:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('El octanaje del combustible en la compresión en un motor alternativo mantiene una de las siguientes relaciones:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('La viscosidad del aceite depende de:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si una fuente estática de un altímetro se bloquea durante un ascenso:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando se mueve la palanca de mezcla a una posición de mezcla pobre:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('La estela de una hélice será mas acusada cuando',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('En relación a la cilindrada del motor',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('La relación combustible/aire que penetra en un motor es una relación de',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un avión de hélice de paso fijo, al aumentar la velocidad del mismo',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si durante un ascenso la toma estática se bloquea, el anemómetro',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un avión con indicador de EGT nos será útil para',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('El indicador de velocidad verdadera del avión ASI',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Que afecta al funcionamiento de los giróscopos:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('En el momento del despegue como se encuentran las palancas de paso y gases',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Para variar la potencia en un avión de hélice de velocidad constante actuaremos:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un motor de explosión, la chispa que produce la ignición se producirá antes o después de punto muerto superior',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Como se llama el error del altímetro producido en la toma de presión estática por su posición cerca de la fuente',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Como se llaman las velocidades que limitan el arco amarillo de un anemómetro',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('La formula correcta para calcular el desplazamiento de un motor multicilíndrico es:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('Para cambiar de potencia en motores alternativos dotados de hélices de velocidad constante, y así evitar  la sobrecarga del motor, actuaremos:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Que velocidad es la que marca el límite inferior del arco blanco de un ASI?',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('La combinación correcta de paso de hélice (1), y posición de palanca de hélice (2), en el momento de soltar   frenos para el despegue es:',8);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Que significa AFIS?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cual de los siguientes canales puede usarse para transmitir un ATIS',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Que significa “GO AHEAD”',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si debemos contestar “SI” usaremos',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una estación aeronáutica nos informa sobre la visibilidad de un aeropuerto¿Que unidades de medida empleará?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si una estación aeronáutica nos pide que colacionemos un mensaje quiere decir',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un FIR es:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué significa QDM?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es el código Q para “marcación verdadera desde la emisora?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es la forma correcta de transmitir y verificar la transmisión de 120375 MHz (canal VHF separado por 25 Khz)?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un mensaje será más efectivo y más fácil de comprender si:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué significa tener una buena técnica al micrófono?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es el indicativo en radiotelefonía para la estación que presta servicios de control de movimientos en superficie de las aeronaves en la zona de maniobras?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al avión se le ordena mantener su posición antes de entrar a pista en servicio¿Qué frase es correcta?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cómo transmitimos 1001 como QNH?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('La expresión “dispersas” en meteorología hace referencia a:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Indíquese qué código se debe seleccionar en el transponder para indicar un fallo en las 4',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cómo debe hacerse una transmisión ciega (Blind Transmision)?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es la máxima distancia de VHF sobre  terreno llano a FL 050?:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una aeronave en emergencia responderá en:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cómo debe informar un piloto a torre que se encuentra “Listo para el despegue”?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué significa la frase Recibido (Roger)?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('La autorización “Autorizado para su despegue inmediato en pista 03” es:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué significa “inteligibilidad 3”?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué mensajes no pueden transmitirse?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué elementos deben siempre colacionarse en un mensaje?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Como se expresara en radiotelefonía  “espere le  llamare”?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué frase deberá emplear un piloto que quiera decir entiendo su mensaje y procederé a su cumplimiento?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿En qué frecuencia se da la primera señal de socorro “MAY DAY”?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuándo la torre podrá decir el distintivo de llamada abreviado?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es la distancia máxima a la que puede esperarse un buen contacto UHF sobre terreno llano y a nivel de vuelo FL100?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué se utiliza habitualmente para las emisiones ATIS?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se define urgencia como:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Significado de “HJ”:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('En caso de fallo de radio volando en VFR dentro de espacio aéreo controlado',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué afecta a la señal VHF?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué es colacionar?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Que frase deberá emplear un piloto que quisiera decir:  “SI”:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cómo se indica la visibilidad horizontal?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Significado de “GO AHEAD”:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si a un piloto se le solicita que comunique su altura, ¿a qué código Q se remitirá?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('La prioridad de la orden ruede hasta la pista 05 es:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué abreviatura se utiliza para el término zona de control?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué código Q se utiliza para comunicar la altitud?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Durante la transmisión de números que contengan puntos decimales:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al avión XBC se le ha ordenado contactar con torre  de Stifer Bil en la frecuencia 1187, ¿Cuál es la respuesta correcta para indicar que cumple la orden recibida?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué frase deberá emplear un piloto que precisa que le sea repetido un mensaje en su totalidad?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un avión no consigue establecer contacto por radio con una estación determinada de frecuencia designada, ¿Qué deberá hacer el piloto?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Como será la abreviatura radiotelefónica de la matricula EC-AXD',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es el código Q para marcación magnética desde la estación?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un mensaje relativo a un avión bajo amenaza de peligro grave e inminente, que requiere ayuda de inmediato, se denomina:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es la forma correcta de deletrear HB-JYC en un mensaje por radio?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué significa la frase “Colaccione” (Read back)?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Que  frase deberá emplear un piloto que quisiera decir: “entiendo su mensaje y procederé a su cumplimiento”',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué significa la orden: “motor  y al aire” (go around)',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando se utiliza el termino “buenas condiciones de cielo y visibilidad” (CAVOK) en los informes meteorológicos rutinarios para utilización aeronáutica (METAR), los valores de visibilidad y nubes son:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un avión transmite el código 7600, ello indica que:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al transmitir en vuelo el mensaje precedido de la frase “transmisión ciega debido a fallo en el receptor”, el avión deberá también:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('cual de las siguientes es una frecuencia internacional de emergencia?',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('El mensaje “solicito vectores radar para circunnavegar área de mal tiempo”, dirigido a un centro de control de área es:',4);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es la longitud de la circunferencia de la tierra?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un avión en recalada con un QDM de 0º. Su rumbo magnético cada vez es menor.La aeronave experimenta.',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es el significado del término “hora oficial”?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Derrota verdadera 348, deriva 17ª a la izquierda, declinación 32º W y desvío 4º E.Hallar el rumbo en brújula:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al virar a la derecha desde 330º a 040º en el hemisferio norte, la brújula magnética de lectura directa indica:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es el valor máximo de la declinación?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las líneas de contorno que aparecen en mapas y cartas aeronáuticas:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('La distancia medida entre dos puntos de una carta de navegación es de 42 mm.La escala de la carta es de 1:1.600',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es la distancia  en NM sobre el terreno de 12 cm medidos sobre una carta de escala 1:2.0.000?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Una línea recta trazada sobre la carta mide 4,63 cm y representa 150 NM.Hallar la escala de la carta:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Supuestos TC 180º, TAS 500 Kt W 225/100 Kt.Calcular la GS:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Hallar el tiempo en recorrer 5 NM con una GS de 269 Kt:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('TC 90º, TAS 180 Kt GS180 Kt, deriva 5º a la derecha, Hallar el viento:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Supuesto MH 060º, declinación 8ºW y deriva 4º a la derecha, Hallar TC:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Pista 23 (227 magnético) ATIS 180/30 Kt declinación 13º E.Hallar la componente de viento cruzado:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Volando a baja cota, un avión cruza dos carreteras paralelas con 90º respecto a ellas.El tiempo que tarda en cruzar las carreteras nos servirá para determinar:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se observa una isla 15º a la izquierda.Nuestro rumbo magnético es de 120º, la declinación es de 17º W.Hallar el rumbo verdadero para ir a la isla:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué tipo de carta es cuando se enfoca desde el borde o superficie de la Tierra?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si estamos encima de un VOR/DME a 6.000’, ¿Qué marca el DME?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué es falso en la carta 1:500.000?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Navegando en visual, ¿Qué debes mirar antes, el exterior y luego la carta, o al revés, primero la carta y luego el exterior?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un aeronave que vuela a FL 85 la CAS = 100 Kts y la OAT = 0º, calcular la TAS:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Conociendo TAS = 140, curso verdadero = 120º y viento = 90º/30 Kts calcular el rumbo verdadero y la velocidad sobre el suelo GS:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('La carta cuyo origen de proyección se encuentra a una distancia finita, fuera de la Tierra, recibe el nombre específico de:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('En relación con las cartas, indique cuál de las siguientes frases NO  es cierta:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('El comportamiento errático de la brújula magnética en los polos o en sus cercanías se debe a:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cualquier plano que no pase por el centro de la Tierra forma en la intersección con la superficie de esta:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('El sistema de navegación omnidireccional que opera en la banda de frecuencia de VHF recibe el nombre de:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('El radiocompás funciona en la gama de frecuencias:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('El símbolo cartográfico OACI “ O”  indica la existencia de:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cómo expresamos la dirección de desplazamiento en avión?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si nos quedan 45 minutos de autonomía, nos quedan 60 NM para llegar a destino y nuestra TAS es de 90 nudos,  suponemos viento cero, ¿Podremos llegar a destino o habrá que buscar alternativo?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('La inclinación del eje de la tierra determina entre otras cosas las estaciones del año, la duración del día en distintas latitudes etc., pero ¿Cuál  es el valor de la inclinación en grados?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Los meridianos son:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué es un línea isogona?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué es una línea agónica?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es la diferencia de latitud entre el punto 60º norte y el 20º sur?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué se entiende por navegación a la estima?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Identificar la frase correcta en caso de estar perdidos en mitad de una ruta:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Legalmente debemos dejar una reserva de combustible para realizar esperas sobre el aeródromo de destino y alternativo, ¿De cuanto tiempo es esta reserva?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si entre A y B consumimos 5 galones de combustible y el tiempo de vuelo entre A y B es de 40 minutos y nos quedan 15 galones de combustible, ¿Cuánto tiempo de vuelo nos queda?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('El VOR emite radiales que nos permiten acercarnos, alejarnos o simplemente establecer nuestra posición, estos radiales están orientados según:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Si navegamos manteniendo centrado el CDI del VOR con un radial de acercamiento o una ruta de alejamiento, la deriva producida por el viento es compensada',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿De qué antenas  consta el equipo ADF  de abordo?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un ADF, ¿A qué se le llama P?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Dentro del código Q, ¿Cómo se escribe la marcación magnética para ir a la estación?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿En qué consiste el efecto tormenta del ADF?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué equipo de radar en tierra necesita un equipo transpondedor a bordo del avión para que los controladores reciban otros tipos de información del tráfico aparte de su eco?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('En caso de estar perdidos, ¿Cómo podemos localizar nuestro punto exacto de posición en una carta?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿cuál de los siguientes no es un error propio del ADF?:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Volamos a nivel de vuelo 85 con una CAS de 120 Kt, una IAT = -10ºC',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('La brújula de un avión que se acerca al polo, marcará:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Con rumbo 000º la aguja de ADF marca 120º a la izquierdaHallar el giro que debemos hacer para que suba la cola:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un avión vuela con rumbo 180º con el CDI centrado en 120º TOHallar en qué radial se encuentra:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Volamos con rumbo 075º y el ADF nos empieza a marcar lentamente 075º, 080º, 085º, 090º¿Qué conclusión podemos sacar?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué tipo de proyección es la que tiene el punto de vista a una distancia finita de la superficie de la tierra?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('A nivel de vuelo 100, ¿Qué distancia puede alcanzar un equipo de 4?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Los polos magnéticos no coinciden con los geográficos:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('El VOR emite en frecuencias:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuánto tardaremos en volar 50 millas si mantenemos una GS de 150 Kt?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Podemos medir rumbos y distancias directamente en una carta Mercator?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál de los siguientes es incorrecto respecto a los GPS?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('El error de la brújula es máximo:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué tipo de frecuencias utilizan los radares primarios?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('En la carta OACI:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se entiende por la desviación de la brújula en ángulo que forman:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un avión vuela siguiendo una derrota verdadera de 048º a una TAS constante de 210 Kt.La velocidad del viento es 350º/30 Kt.La GS y el ángulo  de deriva son:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('La definición de OACI respecto a la abreviatura ETA es:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Supuestos:
Rumbo magnético 311º.Ángulo de deriva 10º a la izquierda Marcación relativa de NDB 270 º.¿Cuál es la marcación magnética del NDB medida desde el avión?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Suponiendo viento cero.¿Qué distancia cubrirá una aeronave que descienda 15000 pies con una TAS de 320 Kt y manteniendo un régimen de descenso de 3¿Cuál es la marcación magnética del NDB medida desde el avión?',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Rumbo indicado de brújula 270, desviación 2º W, declinación 30º E, marcación relativa 316Calcular el QDR:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Rumbo verdadero 090, TAS 220 Kt, viento 220º/30Kt, Calcular la GS:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Ruta magnética 225º, variación 40º W, GS= 375 Kt, Viento 235/120Kt, Calcular el ángulo de deriva:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('TAS 220 Kt, Ruta magnética 212 º, viento 160/50 Kt, Calcular la GS:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('TAS 470 Kt, Ruta verdadero 317º, viento 045º/45 Kt, Calcular el ángulo de deriva y la velocidad respecto al suelo:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('La velocidad respecto al suelo es de 105 Kt, la distancia entre A y B son 103 NM, Calcular el tiempo entre A y B:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al decelerar el rumbo W en el hemisferio Norte la tarjeta de una brújula magnética de lectura directa girará:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Suponiendo rumbo verdadero 074, TAS 230, derrota 066, velocidad respecto al suelo 242Kts, calcular la dirección y velocidad del viento:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('Cuando seguimos un radial VOR:',9);
INSERT INTO questions(string_question,id_category_question) VALUES ('De las siguientes que situación conduce a una disminución de la velocidad de perdida en términos de IAS:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al retraer los flaps con ángulo de ataque constante, el avión:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al extender los flaps con ángulo de ataque constante, el avión:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('La capa limite esta causada por :',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un avión normal y estable, el centro de gravedad esta situado',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Para compensar una guiñada negativa (guiñada adversa), el avión dispone de',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('El factor de carga es',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un avión desciende a una velocidad constante de 160 KIAS a un régimen de descenso de 1000 Ft/minuto cual de las siguientes afirmaciones es verdadera',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Que capa limite tiene mayor variación de velocidad cerca de la superficie',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un avión en vuelo recto  nivelado con el mismo ángulo de ataque, en ISA y a dos alturas distintas experimentará',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('El efecto suelo influye en la distancia de aterrizaje',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('La presión estática actúa',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Al seleccionar flaps en vuelo recto y nivelado con IAS constante aumenta',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('El alabeo es una rotación sobre el eje',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('La rotación sobre el eje lateral es',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('La fuerza de sustentación actúa sobre una superficie aerodinámica',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('La sustentación y la resistencia aerodinámica sobre un perfil se consideran vertical y paralela',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Se define capa limite',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Para mantener un vuelo recto y nivelado a velocidad relativa constante, mientras se retraen los flaps, el ángulo de ataque deberá:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué objeto tiene el sistema de SLATS automáticos?',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('La resistencia aerodinámica al avance de un cuerpo colocado en una determinada corriente de aire depende:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál es la medida de presión utilizada en aviación?',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('El ángulo de ataque, ángulo de incidencia aerodinámica, de una superficie aerodinámica es el ángulo comprendido entre:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('El ángulo entre el eje longitudinal del avión y la dirección de la cuerda es:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál de las siguientes afirmaciones con respecto a la relación sustentación/resistencia en vuelo recto y nivelado es correcta?',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Durante despegue, en el momento que la aeronave levanta las ruedas de suelo:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Durante un viraje la sustentación necesaria:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('En el diagrama polar de todo el avión puede leerse:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Cuál de los siguientes dispositivos se emplean como avisadores de entrada en pérdida?',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('La resistencia aerodinámica se considera paralela a',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué es lo que sucede ante el efecto suelo?',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un flap simple aumenta el CL máximo cuando:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué fórmula o ecuación describe la relación: La fuerza F, la aceleración A y la masa M?',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Qué factores determinan la distancia respecto al suelo recorrido por un avión al planear?',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('La sustentación de un avión de peso W en ascenso lineal constante manteniendo un ángulo de ascenso Gama es aproximadamente:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('La sustentación se produce cuando:',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Que ocurrirá con la densidad de un fluido si este se ve obligado a pasar por un tubo que tiene una sección menor',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Las unidades utilizadas en el Sistema Internacional para la medida de la densidad y la fuerza son respectivamente',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Un avisador de perdida de paleta actúa cuando sobre él',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('La velocidad de mínimo descenso',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿ Que representa la X en ese eje?',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('¿Que es lo mas determinante para la generación de resistencia inducida?',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('En un perfil con cierta comba y ángulo de ataque positivo, ¿en que lugar tendrá mas velocidad el flujo de aire?',5);
INSERT INTO questions(string_question,id_category_question) VALUES ('Dada la ecuación de los gases perfectos, ¿cómo afecta a la densidad (rho) de una corriente de aire un cambio en el área de un tubo por el que se le hace pasar, suponiendo condiciones estándar?',5);
